# Weathered copper with layered verdigris, oxide mottling and microscopic pits.
ResetMaterial()
coord = TextureCoordinate(alias="coord", location=(-1500, 100))
macro = NoiseTexture(alias="macro", name="Oxidation Islands", scale=3.8, detail=5.0, roughness=0.7, location=(-1220, 500))
grain = NoiseTexture(alias="grain", name="Corrosion Grain", scale=42.0, detail=3.0, roughness=0.75, location=(-1220, 80))
micro = NoiseTexture(alias="micro", name="Metal Microtexture", scale=180.0, detail=2.0, roughness=0.6, location=(-1220, -350))
pits = VoronoiTexture(alias="pits", name="Corrosion Pits", scale=85.0, location=(-1220, -750))
Link(coord, "Generated", macro, "Vector")
Link(coord, "Generated", grain, "Vector")
Link(coord, "Generated", micro, "Vector")
Link(coord, "Generated", pits, "Vector")
mask_mix = MixRGB(alias="mask_mix", name="Broken Oxide Borders", blend_type="MULTIPLY", factor=0.35, location=(-920, 550))
Link(macro, "Fac", mask_mix, "Color1")
Link(grain, "Fac", mask_mix, "Color2")
mask = ColorRamp(alias="mask", name="Patina Coverage", location=(-670, 650), stops=[(0.28,(0,0,0,1)),(0.47,(1,1,1,1))])
Link(mask_mix, "Color", mask, "Fac")
copper_color = ColorRamp(alias="copper_color", name="Warm Copper Alloy", location=(-660, 320), stops=[(0.2,(0.16,0.045,0.012,1)),(0.8,(0.62,0.27,0.095,1))])
Link(grain, "Fac", copper_color, "Fac")
oxide_color = ColorRamp(alias="oxide_color", name="Verdigris Pigment", location=(-650, -20), stops=[(0.15,(0.008,0.038,0.022,1)),(0.48,(0.025,0.16,0.105,1)),(0.82,(0.14,0.38,0.25,1))])
Link(grain, "Fac", oxide_color, "Fac")
metal_roughness = ColorRamp(alias="metal_roughness", name="Metal Roughness", location=(-650,-360), stops=[(0.1,(0.19,0.19,0.19,1)),(0.9,(0.43,0.43,0.43,1))])
Link(micro, "Fac", metal_roughness, "Fac")
oxide_roughness = ColorRamp(alias="oxide_roughness", name="Powder Roughness", location=(-650,-670), stops=[(0.15,(0.62,0.62,0.62,1)),(0.85,(0.88,0.88,0.88,1))])
Link(grain, "Fac", oxide_roughness, "Fac")
pit_shape = ColorRamp(alias="pit_shape", name="Pit Profile", location=(-900,-980), stops=[(0.06,(0,0,0,1)),(0.29,(0.7,0.7,0.7,1)),(0.52,(1,1,1,1))])
Link(pits, "Distance", pit_shape, "Fac")
micro_bump = Bump(alias="micro_bump", name="Fine Hammering", strength=0.2, distance=0.018, location=(-320,-620))
Link(micro, "Fac", micro_bump, "Height")
pit_bump = Bump(alias="pit_bump", name="Pitted Copper", strength=0.26, distance=0.025, location=(-50,-620))
Link(pit_shape, "Color", pit_bump, "Height")
Link(micro_bump, "Normal", pit_bump, "Normal")
oxide_bump = Bump(alias="oxide_bump", name="Raised Oxide Crust", strength=0.32, distance=0.055, location=(210,-480))
Link(mask, "Color", oxide_bump, "Height")
Link(pit_bump, "Normal", oxide_bump, "Normal")
copper = PrincipledBSDF(alias="copper", name="Exposed Copper", metallic=1.0, coat_weight=0.08, coat_roughness=0.28, location=(200,550))
Link(copper_color, "Color", copper, "Base Color")
Link(metal_roughness, "Color", copper, "Roughness")
Link(pit_bump, "Normal", copper, "Normal")
oxide = PrincipledBSDF(alias="oxide", name="Porous Verdigris", metallic=0.05, specular_ior_level=0.28, location=(200,50))
Link(oxide_color, "Color", oxide, "Base Color")
Link(oxide_roughness, "Color", oxide, "Roughness")
Link(oxide_bump, "Normal", oxide, "Normal")
layer = MixShader(alias="layer", name="Copper and Patina", location=(620,400))
Link(mask, "Color", layer, 0)
Link(copper, "BSDF", layer, 1)
Link(oxide, "BSDF", layer, 2)
output = OutputMaterial(location=(900,400))
Link(layer, 0, output, "Surface")
